export const GET_CONFIG = 'get_config'; //Get the config options
export const MAIN_LOADING = 'main_loading'; //Main Loading on/off
export const INITIALIZE = 'initialize'; //Initialize state for googlemap ref to be working
export const CHANGE_DATE = 'change_date'; // Change depart date
export const DELETE_DATE = 'delete_date'; // Clear date
export const CALCUL_DATE = 'calcul_date'; // Apply dates to every places
export const GET_DATE = 'get_date'; // Get dates
export const SELECT_PLACE = 'select_place'; //Select a place to go
export const GET_PLACES = 'get_places'; //Get the places state
export const ADD_PLACE = 'add_place'; //Add a place to the places state
export const DELETE_PLACE = 'delete_place'; //Add a place to the places state
export const GET_TRIP = 'get_trip'; //Get the trip state
export const GET_ROUTES = 'get_routes'; //Get the routes from the Search script from point A to point B
export const CHOOSE_ROUTE = 'choose_route'; //Select one of the proposed routes
export const DELETE_ROUTE = 'delete_route'; //Delete route
export const CLEAR_ROUTE = 'clear_route'; //Only delete the rotue choice
export const MOVEPLACE_UP = 'moveplace_up'; // Move a place up in the order
export const MOVEPLACE_DOWN = 'moveplace_down'; // Move a place down in the order
export const CHANGE_ITINERARY = 'change_itinerary'; // Select another itinerary
export const SHOW_MARKER = 'show_marker'; // Show marker info window
export const CLOSE_MARKER = 'close_marker'; // Hide marker info window
export const CHECK_OPTION = 'check_option'; // Check an option
export const CHECK_MAPOPTION = 'check_mapoption'; // Check a map option